{{- $webapp := .Values.georchestra.webapps.openldap -}}
{{- if $webapp.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-ldap
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
spec:
  replicas: {{ $webapp.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-ldap
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-ldap
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
      - name: georchestra-ldap
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        env:
          - name: SLAPD_ORGANISATION
            value: georchestra
          - name: SLAPD_DOMAIN
            value: georchestra.org
          - name: RUN_AS_UID
            value: "0"
          - name: RUN_AS_GID
            value: "0"
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        # Load the ldap admin password from a secret. Can also allow to override some other env vars with env vars defined in this secret, like for instance the GEORCHESTRA_PRIVILEGED_USER_PASSWORD
        envFrom:
          - secretRef:
              name: {{ .Values.ldap.existingSecret | default (printf "%s-ldap-passwords-secret" (include "georchestra.fullname" .)) | quote }}
        ports:
        - containerPort: {{ .Values.ldap.port }}
          name: ldap
        volumeMounts:
          - mountPath: /etc/ldap
            name: openldap-config
          - mountPath: /var/lib/ldap
            name: openldap-data
          {{- if $webapp.extraVolumeMounts }}
            {{- toYaml $webapp.extraVolumeMounts | nindent 10 }}
          {{- end }}
        livenessProbe:
          exec:
            command:
            - ldapsearch
            - -x
            - -Hldap://localhost:{{ .Values.ldap.port }}/
            - -b{{ .Values.ldap.baseDn }}
            - {{ .Values.ldap.adminDn }}
          initialDelaySeconds: 30
      {{- if $webapp.extraContainers }}
        {{ toYaml $webapp.extraContainers | nindent 6 }}
      {{- end }}
      volumes:
      - name: openldap-data
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-openldap-data
      - name: openldap-config
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-openldap-config
      {{- if $webapp.extraVolumes }}
          {{- toYaml $webapp.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
