version: 2
updates:
  - package-ecosystem: "helm"
    directory: "/georchestra"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/maelstro"
    schedule:
      interval: "weekly"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: "weekly"
