{{- $webapp := .Values.georchestra.webapps.geonetwork.ogc_api_records -}}
{{- if and .Values.georchestra.webapps.geonetwork.enabled $webapp.enabled -}}
{{- $database := .Values.database -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        fsGroup: 999
      initContainers:
      {{- include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      {{- if $webapp.envsubst.enabled }}
      - name: envsubst
        image: georchestra/k8s-initcontainer-envsubst
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        env:
          - name: DEBUG
            value: "yes"
          - name: SUBST_FILES
            value: "/etc/georchestra/geonetwork/microservices/ogc-api-records/config.yml"
          {{- include "georchestra.service-envs" . | nindent 10 }}
          {{- include "georchestra.common-envs" . | nindent 10 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
      {{- end }}

      containers:
      - name: ogc-api-records
        image: {{ $webapp.image }}
        env:
          - name: LANG
            value: en_US.UTF-8
          - name: SERVER_SERVLET_CONTEXT_PATH
            value: /ogc-api-records
          - name: SPRING_CONFIG_LOCATION
            value: file:///etc/georchestra/geonetwork/microservices/ogc-api-records/config.yml
          - name: SPRING_PROFILES_ACTIVE
            value: standalone
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}?user=${PGUSER}&currentSchema=geonetwork
          - name: SPRING_DATASOURCE_PASSWORD
            value: ${PGPASSWORD}
          {{- include "georchestra.service-envs" . | nindent 10 }}
          {{- include "georchestra.common-envs" . | nindent 10 }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end -}}
