{{- $webapp := .Values.georchestra.webapps.geoserver -}}
{{- if $webapp.enabled -}}
{{- $database := .Values.database -}}
{{- $database_secret_geodata_name := printf "%s-database-geodata-secret" (include "georchestra.fullname" .) -}}
{{- $database_secret_datafeeder_name := printf "%s-database-datafeeder-secret" (include "georchestra.fullname" .) -}}
{{- $database_secret_gwc_name := printf "%s-database-georchestra-secret" (include "georchestra.fullname" .) -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-geoserver
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
spec:
  replicas: {{ $webapp.replicaCount }}
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-geoserver
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-geoserver

      {{- if $webapp.jetty_monitoring }}
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "9103"
        prometheus.io/scrape: "true"
      {{- end }}
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
        {{- with .Values.georchestra.nodeSelector }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      securityContext:
        fsGroup: 999
      initContainers:
      {{ include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      - name: fix-permissions-pvc
        image: busybox:latest
        command: ["sh", "-c", "chown -R 999:999 /mnt/geoserver_datadir /mnt/geoserver_geodata /mnt/geoserver_tiles"]
        volumeMounts:
        - mountPath: /mnt/geoserver_datadir
          name: geoserver-datadir
        - mountPath: /mnt/geoserver_geodata
          name: geoserver-geodata
        - mountPath: /mnt/geoserver_tiles
          name: geoserver-tiles
      containers:
      - name: georchestra-geoserver
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        env:
          {{ if $database.builtin }}
          - name: GEODATA_PGHOST
            value: "{{ .Release.Name }}-database"
          - name: GEODATA_PGDATABASE
            value: "geodata"
          {{ else }}
          {{ if $database.geodata.auth.existingSecret }}
          {{- $database_secret_geodata_name = $database.geodata.auth.existingSecret -}}
          {{ end }}
          - name: GEODATA_PGHOST
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_geodata_name }}
                  key: host
                  optional: false
          - name: GEODATA_PGDATABASE
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_geodata_name }}
                  key: dbname
                  optional: false
          {{ end }}
          - name: GEODATA_PGPORT
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_geodata_name }}
                  key: port
                  optional: false
          - name: GEODATA_PGUSER
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_geodata_name }}
                  key: user
                  optional: false
          - name: GEODATA_PGPASSWORD
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_geodata_name }}
                  key: password
                  optional: false
          {{ if $database.builtin }}
          - name: DF_PGHOST
            value: "{{ .Release.Name }}-database"
          - name: DF_PGDATABASE
            value: "datafeeder"
          {{ else }}
          {{ if $database.datafeeder.auth.existingSecret }}
          {{- $database_secret_datafeeder_name = $database.datafeeder.auth.existingSecret -}}
          {{ end }}
          - name: DF_PGHOST
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_datafeeder_name }}
                  key: host
                  optional: false
          - name: DF_PGDATABASE
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_datafeeder_name }}
                  key: dbname
                  optional: false
          {{ end }}
          - name: DF_PGPORT
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_datafeeder_name }}
                  key: port
                  optional: false
          - name: DF_PGUSER
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_datafeeder_name }}
                  key: user
                  optional: false
          - name: DF_PGPASSWORD
            valueFrom:
              secretKeyRef:
                  name: {{ $database_secret_datafeeder_name }}
                  key: password
                  optional: false
          {{ if $database.builtin }}
          - name: GWC_PGHOST
            value: "{{ .Release.Name }}-database"
          {{- else }}
          {{ if $database.auth.existingSecret }}
          {{- $database_secret_gwc_name = $database.auth.existingSecret -}}
          {{ end }}
          - name: GWC_PGHOST
            valueFrom:
              secretKeyRef:
                name: {{ $database_secret_gwc_name }}
                key: host
                optional: false
          {{- end }}
          - name: GWC_PGPORT
            valueFrom:
              secretKeyRef:
                name: {{ $database_secret_gwc_name }}
                key: port
                optional: false
          - name: GWC_PGDATABASE
            valueFrom:
              secretKeyRef:
                name: {{ $database_secret_gwc_name }}
                key: dbname
                optional: false
          - name: GWC_PGUSERNAME
            valueFrom:
              secretKeyRef:
                name: {{ $database_secret_gwc_name }}
                key: user
                optional: false
          - name: GWC_PGPASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ $database_secret_gwc_name }}
                key: password
                optional: false
          - name: GEOSERVER_CSRF_WHITELIST
            value: {{ .Values.fqdn }}
          {{- include "georchestra.database-georchestra-envs" . | nindent 10 }}
          {{- if $webapp.extra_environment }}
          {{- $webapp.extra_environment | toYaml | nindent 10 }}
          {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /mnt/geoserver_geodata
            name: geoserver-geodata
          - mountPath: /mnt/geoserver_datadir
            name: geoserver-datadir
          - mountPath: /mnt/geoserver_tiles
            name: geoserver-tiles
          {{- if $webapp.extra_volumeMounts }}
            {{ $webapp.extra_volumeMounts | toYaml | nindent 10 }}
          {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        {{- if $webapp.custom_liveness_probe }}
        {{ $webapp.custom_liveness_probe | toYaml | nindent 8 }}
        {{- else }}
        livenessProbe:
          httpGet:
            path: /geoserver/ows?SERVICE=WMS&LAYERS=geor:public_layer&FORMAT=image/png&VERSION=1.3.0&SLD_VERSION=1.1.0&REQUEST=GetMap&CRS=EPSG:3857&BBOX=-20820223,-20820223,20820223,20820223&WIDTH=10&HEIGHT=10
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 5
        {{- end }}
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 40
      {{- if $webapp.jetty_monitoring }}
      - name: jmx-collectd
        image: camptocamp/jmx-collectd:bullseye
        volumeMounts:
        - mountPath: /collectd-template
          name: georchestra-monitoring-cm
        ports:
        - containerPort: 9103
          name: prometheus
        command:
        - /bin/sh
        - -c
        - mkdir /etc/collectd/collectd.conf.d/ ;
          cat /collectd-template/collectd-jmx-jetty.conf | sed "s/localhost/$(hostname)/g" > /etc/collectd/collectd.conf.d/jmx.conf ;
          collectd -f
      {{- end }}
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: geoserver-tiles
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geoserver-tiles
      - name: geoserver-geodata
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geoserver-geodata
      - name: geoserver-datadir
        persistentVolumeClaim:
          claimName: {{ include "georchestra.fullname" . }}-geoserver-datadir
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.extra_volumes }}
        {{ $webapp.extra_volumes | toYaml | nindent 6 }}
      {{- end }}
      {{- if $webapp.jetty_monitoring }}
      - name: georchestra-monitoring-cm
        configMap:
          name: {{ include "georchestra.fullname" . }}-monitoring-cm
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
      {{- if $webapp.tolerations }}
      tolerations:
        {{- $webapp.tolerations | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.hostAliases }}
      hostAliases:
        {{- .Values.hostAliases | toYaml | nindent 8 }}
      {{- end }}
{{- end }}
