{{- if .Values.georchestra.webapps.cas.enable -}}
{{- $webapp := .Values.georchestra.webapps.cas -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-cas
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-cas
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-cas
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      initContainers:
      {{- include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      - name: prepare-cas-webapp
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
        - mountPath: /cas-webapp
          name: cas-webapp
        command:
        - /bin/sh
        - -c
        - cp -r /var/lib/jetty/webapps/cas/* /cas-webapp ;
          if [ -d /etc/georchestra/cas/themes ] ; then
            cp -rvf /etc/georchestra/cas/themes /cas-webapp/WEB-INF/classes/static/ ;
          fi ;
          if [ -d /etc/georchestra/cas/templates ] ; then
            cp -rvf /etc/georchestra/cas/templates /cas-webapp/WEB-INF/classes/ ;
          fi
      containers:
      - name: georchestra-cas
        image: {{ $webapp.docker_image }}
        imagePullPolicy: Always
        {{- if $webapp.extra_environment }}
        env:
          {{- $webapp.extra_environment | toYaml | nindent 8 }}
        {{- end }}
        volumeMounts:
          - mountPath: /etc/georchestra
            name: georchestra-datadir
          - mountPath: /var/lib/jetty/webapps/cas
            name: cas-webapp
        ports:
        - containerPort: 8080
          name: http-proxy
        livenessProbe:
          httpGet:
            path: /cas/login
            port: 8080
          periodSeconds: 10
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 5
          periodSeconds: 60
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      - name: cas-webapp
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
      {{- if $webapp.registry_secret }}
      imagePullSecrets:
      - name: {{ $webapp.registry_secret }}
      {{- end }}
{{- end }}
