{{- if and .Values.georchestra.webapps.geonetwork.enable .Values.georchestra.webapps.geonetwork.ogc_api_records.enable -}}
{{- $webapp := .Values.georchestra.webapps.geonetwork.ogc_api_records -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
  labels:
    {{- include "georchestra.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "georchestra.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
  template:
    metadata:
      labels:
        {{- include "georchestra.selectorLabels" . | nindent 8 }}
        org.georchestra.service/name: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
        app.kubernetes.io/component: {{ include "georchestra.fullname" . }}-gn4-ogc-api-records
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      securityContext:
        fsGroup: 999
      initContainers:
      {{- include "georchestra.bootstrap_georchestra_datadir" . | nindent 6 }}
      containers:
      - name: ogc-api-records
        image: {{ $webapp.image }}
        env:
        - name: LANG
          value: en_US.UTF-8
        - name: SERVER_SERVLET_CONTEXT_PATH
          value: /ogc-api-records
        - name: SPRING_CONFIG_LOCATION
          value: file:///etc/georchestra/geonetwork/microservices/ogc-api-records/config.yaml
        - name: SPRING_PROFILES_ACTIVE
          value: standalone
        {{- with $webapp.env_variables }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - containerPort: 8080
          name: http-proxy
        volumeMounts:
        - mountPath: /etc/georchestra
          name: georchestra-datadir
      volumes:
      - name: georchestra-datadir
        emptyDir: {}
      {{- if .Values.georchestra.datadir.git.ssh_secret }}
      - name: ssh-secret
        secret:
          secretName: {{ .Values.georchestra.datadir.git.ssh_secret }}
          defaultMode: 0400
      {{- end }}
{{- end -}}
